dateModified: 1550662451
email:
  fromEmail: andrecorreia.drible@gmail.com
  fromName: 'We Are Drible'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  d80a6993-59a6-40cf-ba16-58860e29c890:
    name: Common
fields:
  62aa662d-997b-4226-be5a-cb4c0dc8c919:
    contentColumnType: string
    fieldGroup: d80a6993-59a6-40cf-ba16-58860e29c890
    handle: adicionar
    instructions: ''
    name: Conteudo
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_adicionar}}'
      localizeBlocks: false
      maxBlocks: ''
      minBlocks: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
matrixBlockTypes:
  4455bf9b-dec9-4f29-b495-eb3f6d7d47fe:
    field: 62aa662d-997b-4226-be5a-cb4c0dc8c919
    fieldLayouts:
      cfcd56c4-c4b8-4c9d-800c-241ea28458f7:
        tabs:
          -
            fields:
              5142ce04-acfc-44a4-be16-7f2a7452a24b:
                required: '0'
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      5142ce04-acfc-44a4-be16-7f2a7452a24b:
        contentColumnType: text
        fieldGroup: null
        handle: conteudo
        instructions: ''
        name: Conteudo
        searchable: '1'
        settings:
          availableTransforms: '*'
          availableVolumes: '*'
          cleanupHtml: '1'
          columnType: text
          purifierConfig: ''
          purifyHtml: '1'
          redactorConfig: Standard.json
        translationKeyFormat: null
        translationMethod: none
        type: craft\redactor\Field
    handle: conteudo
    name: Conteudo
    sortOrder: 1
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
sections:
  02a0d967-4c6b-4c11-b5d1-98fd4539bc4b:
    enableVersioning: true
    entryTypes:
      eef536a9-44d1-43e3-b9af-9ce7fef29ed5:
        fieldLayouts:
          7ef676e3-7a7a-433f-9e7a-cd505b5ca8a8:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Processos
                sortOrder: 1
        handle: webprocessos
        hasTitleField: true
        name: Webprocessos
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: webprocessos
    name: Webprocessos
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'webprocessos/{slug}'
    type: channel
  2aa082f4-7ddf-480d-9505-71928d0cce16:
    enableVersioning: true
    entryTypes:
      321a12cf-b63e-4928-bce3-9e53c023f557:
        fieldLayouts:
          24223f81-477f-432c-b175-5cdff51d3484:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Web
                sortOrder: 1
        handle: estagiariosweb
        hasTitleField: true
        name: estagiariosweb
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: estagiariosweb
    name: estagiariosweb
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'estagiariosweb/{slug}'
    type: channel
  2af9443c-d1f5-4fab-a950-56fa0f916c9c:
    enableVersioning: true
    entryTypes:
      0a93a963-c882-4390-b8f8-7c1df237275a:
        fieldLayouts:
          a8fac8e5-fa9b-4cb8-a975-809ae749a6fd:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Inicio
                sortOrder: 1
        handle: estagiariosinicio
        hasTitleField: true
        name: estagiariosinicio
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: estagiariosinicio
    name: estagiariosinicio
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'estagiariosinicio/{slug}'
    type: channel
  3e2c251e-47e5-4d54-b710-219241a40fd3:
    enableVersioning: true
    entryTypes:
      e7079a23-553a-48c0-92a8-b0d2f6ef9c24:
        fieldLayouts:
          ca39f9af-4dfe-4396-a279-753a3f43f848:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Desgin
                sortOrder: 1
        handle: estagiariosdesign
        hasTitleField: true
        name: estagiariosdesign
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: estagiariosdesign
    name: estagiariosdesign
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'estagiariosdesign/{slug}'
    type: channel
  449613a1-93d9-450b-90bc-a49cf2bf5348:
    enableVersioning: true
    entryTypes:
      514dfc8a-76e1-4c24-86ed-14df1ddf58c5:
        fieldLayouts:
          7d95a552-175e-4f7d-86bd-fec6be44c9a6:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Scripts
                sortOrder: 1
        handle: webscripts
        hasTitleField: true
        name: Webscripts
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: webscripts
    name: Webscripts
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'webscripts/{slug}'
    type: channel
  5381c9cf-a708-4766-93e0-249c197371ea:
    enableVersioning: true
    entryTypes:
      d00b442c-27d8-42ea-8ec7-606cfdfb8ae1:
        fieldLayouts:
          0dd28056-9c60-4534-bb37-44a740b49e5a:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Inicio
                sortOrder: 1
        handle: webinicio
        hasTitleField: true
        name: Webinicio
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: webinicio
    name: Webinicio
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'web/{slug}'
    type: channel
  5912f87b-0e8b-488b-b74a-605f37987b26:
    enableVersioning: true
    entryTypes:
      3c3fcbe7-6769-4a70-bd9f-225c9103155d:
        fieldLayouts:
          9f6818b6-d7c9-4620-b6b5-b91892e254d8:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: 'Marketing Digital'
                sortOrder: 1
        handle: marketingdigital
        hasTitleField: true
        name: 'Marketing digital'
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: marketingdigital
    name: 'Marketing digital'
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'marketing-digital/{slug}'
    type: channel
  685ce4ee-3104-4cec-b39e-6d39fe16a610:
    enableVersioning: true
    entryTypes:
      4028929c-e6d2-457e-aa4d-de25ae29658d:
        fieldLayouts:
          060fd8e0-24a9-4a80-93d5-d393a7dab265:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Frontend
                sortOrder: 1
        handle: webfrontend
        hasTitleField: true
        name: Webfrontend
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: webfrontend
    name: Webfrontend
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'webfrontend/{slug}'
    type: channel
  83ce53aa-8a13-4498-9442-2ee333f9cbb5:
    enableVersioning: true
    entryTypes:
      40b85c14-b0fe-4614-ba66-0ff278bde55e:
        handle: estagiarios
        hasTitleField: true
        name: estagiarios
        sortOrder: 1
        titleFormat: null
        titleLabel: Título
    handle: estagiarios
    name: Estagiarios
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'estagiarios/{slug}'
    type: channel
  8ee29d97-a5d6-4438-86ed-a41692a85c3a:
    enableVersioning: true
    entryTypes:
      3e9e7519-a13a-4d20-9384-e58e8b31c9ca:
        fieldLayouts:
          01ed8c0e-68d4-42bf-99a5-db177316878f:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Marketing
                sortOrder: 1
        handle: estagiariosmarketing
        hasTitleField: true
        name: estagiariosmarketing
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: estagiariosmarketing
    name: estagiariosmarketing
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'estagiariosmarketing/{slug}'
    type: channel
  ab03ac80-03f4-4c36-ac71-8b38b6716c4e:
    enableVersioning: true
    entryTypes:
      6d6771cd-5cd9-442f-8672-66df34894017:
        fieldLayouts:
          d978dd04-a016-462c-bc6e-0eb89e37a9d2:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Inicio
                sortOrder: 1
        handle: inicio
        hasTitleField: true
        name: inicio
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: inicio
    name: Inicio
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'inicio/{slug}'
    type: channel
  b708524d-72d0-4271-aeab-647e1a015205:
    enableVersioning: true
    entryTypes:
      ed882f61-277c-4585-96c7-0abc5090df11:
        fieldLayouts:
          30ea1834-2ecc-47fb-bb64-23e11659fa8f:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Lastday
                sortOrder: 1
        handle: estagiarioslastday
        hasTitleField: true
        name: estagiarioslastday
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: estagiarioslastday
    name: estagiarioslastday
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'estagiarioslastday/{slug}'
    type: channel
  f2ab9f61-9258-4f69-b1b9-72d4ec042eed:
    enableVersioning: true
    entryTypes:
      212f325c-613f-450c-bb03-fe1a73734b1b:
        fieldLayouts:
          42fbb5aa-d6b0-4adc-bc6b-20e895c8792d:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: 'Tab 1'
                sortOrder: 1
        handle: estagiarioswebdrible
        hasTitleField: true
        name: estagiarioswebdrible
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: estagiarioswebdrible
    name: estagiarioswebdrible
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'estagiarioswebdrible/{slug}'
    type: channel
  fa3ac507-6c8f-4881-8177-ed801e9a46e3:
    enableVersioning: true
    entryTypes:
      b5616e85-a66b-40dd-ab4e-1a5f77eec684:
        fieldLayouts:
          36f2f747-b63b-4ed7-abe8-783c3bca0fcd:
            tabs:
              -
                fields:
                  62aa662d-997b-4226-be5a-cb4c0dc8c919:
                    required: false
                    sortOrder: 1
                name: Design
                sortOrder: 1
        handle: design
        hasTitleField: true
        name: Design
        sortOrder: 1
        titleFormat: ''
        titleLabel: Título
    handle: design
    name: Design
    propagateEntries: true
    siteSettings:
      3e504962-4af6-4a26-bde2-ce55b39496f7:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'design/{slug}'
    type: channel
siteGroups:
  4c8248b8-ac7a-4f7a-ad70-fc5e93513af2:
    name: 'We Are Drible'
sites:
  3e504962-4af6-4a26-bde2-ce55b39496f7:
    baseUrl: '@web/'
    handle: index
    hasUrls: true
    language: pt
    name: Home
    primary: true
    siteGroup: 4c8248b8-ac7a-4f7a-ad70-fc5e93513af2
    sortOrder: 1
system:
  edition: solo
  live: true
  name: 'We Are Drible'
  schemaVersion: 3.1.23
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  fieldLayouts:
    5247ae61-53a0-467c-9de3-6ba2323174b9:
      tabs:
        -
          name: teste
          sortOrder: 1
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  0d4b0993-7f8e-496b-85fa-26a8726d211b:
    handle: img
    hasUrls: true
    name: img
    settings:
      path: '@webroot/img'
    sortOrder: null
    type: craft\volumes\Local
    url: '@web/img'
